#include <stdio.h>
#include "common.h"

/*
 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

void problem_002(void){
	int m =1;
	int n = 0;
	int sum = 0;
	while(n < 4000000){		
		sum += n;		
		n = fibonacci(3*m); /* uses recursive fibonacci function from common.c, only every third fibonacci number is even and thus used */
		m++;
	}
	printf("%i", sum);
	return;
}
