#include <stdio.h>

/*
 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

/* simple recursive function for getting the n:th fibonacci number */
int fibonacci(int n){
	if(n == 0){
		return 0;
	} else if(n == 1){
		return 1;
	} else {
		return (fibonacci(n-2)+fibonacci(n-1));		
	}
}

void problem_002(void){
	int m =1;
	int n = 0;
	int sum = 0;
	while(n < 4000000){		
		sum += n;		
		n = fibonacci(3*m); /* Only every third fibonacci number is even */
		m++;
	}
	printf("%i", sum);
	return;
}
